stages:
  - test
variables:
  DEBIAN_FRONTEND: noninteractive
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin"

test:
  stage: test
  image: debian:sid
  environment:
  script:
    # Debian/Ubuntu docker images contain some docker-specific configs in
    # /etc/apt that mess with the tests, so remove them here first.
    - rm /etc/apt/apt.conf.d/docker*
    - apt-cache gencaches

    - apt update
    - apt install build-essential curl sudo -y
    - curl https://sh.rustup.rs -sSf | sh -- /dev/stdin -y
    - cargo install just
    - just setup-dev
    - just check
    - just leak
